---
- name: Preparing LE
  hosts: dc_hosts
  tasks:
    - name: Create nginx directory
      ansible.builtin.file:
        path: /home/yc-user/nginx/conf
        state: directory
        force: true
        mode: '0755'
      become: true

    - name: Create certbot directory
      ansible.builtin.file:
        path: /home/yc-user/certbot/www
        state: directory
        force: true
        mode: '0755'
      become: true

    - name: Copy nginx files
      become: true
      ansible.builtin.copy:
        src: nginx.conf
        dest: /home/yc-user/nginx/conf/nginx.conf
        mode: '0644'
