name: Deploy New Version
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: false
        default: unknown

env:
  YANDEX_SA_KEY: ${{ secrets.YANDEX_SA_KEY }}
  SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SUBNET_ID: ${{ secrets.SUBNET_ID }}
  SERVICE_ACCOUNT_ID: ${{ secrets.SERVICE_ACCOUNT_ID }}
  FOLDER_ID: ${{ secrets.FOLDER_ID }}
  VM_NAME: ${{ vars.VM_NAME }}
  VM_ZONE: ${{ vars.VM_ZONE }}
  PATH_TO_DOCKER_COMPOSE_FILE: ${{ vars.PATH_TO_DOCKER_COMPOSE_FILE }}
  VM_DATA_DISK_D_NAME: ${{ vars.VM_DATA_DISK_D_NAME }}
  SITE_ADDRESS: ${{ vars.SITE_ADDRESS }}

        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Try to install yc cli and login into yandex cloud
          uses: okar1/yc-cli-install@master
          with:
            SA_KEY: ${{ env.YANDEX_SA_KEY }}

        - name: Deploy app
          run: |
            bash infra/yandex/yandex.sh
            